version: '3.4'
services:
  netbox:
    ports:
    - 8080:8080
    volumes:
      - /home/rajivvishwa/docker/docker_files/netbox/configuration:/etc/netbox/config:z,ro
      - /home/rajivvishwa/docker/docker_files/netbox/media:/opt/netbox/netbox/media:rw
      - /home/rajivvishwa/docker/docker_files/netbox/reports:/opt/netbox/netbox/reports:rw
      - /home/rajivvishwa/docker/docker_files/netbox/scripts:/opt/netbox/netbox/scripts:rw
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
      - /home/rajivvishwa/docker/docker_files/netbox/configuration:/etc/netbox/config:z,ro
      - /home/rajivvishwa/docker/docker_files/netbox/media:/opt/netbox/netbox/media:rw
      - /home/rajivvishwa/docker/docker_files/netbox/reports:/opt/netbox/netbox/reports:rw
      - /home/rajivvishwa/docker/docker_files/netbox/scripts:/opt/netbox/netbox/scripts:rw
  netbox-housekeeping:
    volumes:
      - /home/rajivvishwa/docker/docker_files/netbox/configuration:/etc/netbox/config:z,ro
      - /home/rajivvishwa/docker/docker_files/netbox/media:/opt/netbox/netbox/media:rw
      - /home/rajivvishwa/docker/docker_files/netbox/reports:/opt/netbox/netbox/reports:rw
      - /home/rajivvishwa/docker/docker_files/netbox/scripts:/opt/netbox/netbox/scripts:rw
